$token: azure-native:security/v20220801preview:DefenderForServersGcpOfferingResponseConfiguration
description: configuration for Vulnerability Assessment autoprovisioning
properties:
  type:
    type: string
    description: The Vulnerability Assessment solution to be provisioned. Can be either 'TVM' or 'Qualys'
type: object
