$token: azure-native:apimanagement:AuthenticationSettingsContractResponse
description: API Authentication Settings.
properties:
  oAuth2:
    type: object
    $ref: "#/types/azure-native:apimanagement:OAuth2AuthenticationSettingsContractResponse"
    description: OAuth2 Authentication settings
  oAuth2AuthenticationSettings:
    type: array
    items:
      type: object
      $ref: "#/types/azure-native:apimanagement:OAuth2AuthenticationSettingsContractResponse"
    description: Collection of OAuth2 authentication settings included into this API.
  openid:
    type: object
    $ref: "#/types/azure-native:apimanagement:OpenIdAuthenticationSettingsContractResponse"
    description: OpenID Connect Authentication Settings
  openidAuthenticationSettings:
    type: array
    items:
      type: object
      $ref: "#/types/azure-native:apimanagement:OpenIdAuthenticationSettingsContractResponse"
    description: Collection of Open ID Connect authentication settings included into this API.
type: object
