$token: azure-native:servicelinker:ValueSecretInfoResponse
description: The secret info when type is rawValue. It's for scenarios that user input the secret.
properties:
  secretType:
    type: string
    description: |-
      The secret type.
      Expected value is 'rawValue'.
    const: rawValue
  value:
    type: string
    description: The actual value of the secret.
type: object
required:
  - secretType
