$token: azure-native:migrate/v20220801:DiskEncryptionSetResourceSettingsResponse
description: Defines the disk encryption set resource settings.
properties:
  resourceType:
    type: string
    description: |-
      The resource type. For example, the value can be Microsoft.Compute/virtualMachines.
      Expected value is 'Microsoft.Compute/diskEncryptionSets'.
    const: Microsoft.Compute/diskEncryptionSets
  targetResourceGroupName:
    type: string
    description: Gets or sets the target resource group name.
  targetResourceName:
    type: string
    description: Gets or sets the target Resource name.
type: object
required:
  - resourceType
  - targetResourceName
