$token: azure-native:network:PolicySettingsResponse
description: Defines contents of a web application firewall global configuration.
properties:
  customBlockResponseBody:
    type: string
    description: If the action type is block, customer can override the response body. The body must be specified in base64 encoding.
  customBlockResponseStatusCode:
    type: integer
    description: If the action type is block, customer can override the response status code.
  fileUploadLimitInMb:
    type: integer
    description: Maximum file upload size in Mb for WAF.
  maxRequestBodySizeInKb:
    type: integer
    description: Maximum request body size in Kb for WAF.
  mode:
    type: string
    description: The mode of the policy.
  requestBodyCheck:
    type: boolean
    description: Whether to allow WAF to check request Body.
  state:
    type: string
    description: The state of the policy.
type: object
