$token: azure-native:network/v20220401preview:MonitorConfigResponseCustomHeaders
description: Custom header name and value.
properties:
  name:
    type: string
    description: Header name.
  value:
    type: string
    description: Header value.
type: object
