$token: azure-native:network/v20220401preview:MonitorConfigExpectedStatusCodeRanges
description: Min and max value of a status code range.
properties:
  max:
    type: integer
    description: Max status code.
  min:
    type: integer
    description: Min status code.
type: object
