$token: azure-native:aad/v20221201:DomainSecuritySettingsResponse
description: Domain Security Settings
properties:
  channelBinding:
    type: string
    description: A flag to determine whether or not ChannelBinding is enabled or disabled.
    default: Disabled
  kerberosArmoring:
    type: string
    description: A flag to determine whether or not KerberosArmoring is enabled or disabled.
    default: Disabled
  kerberosRc4Encryption:
    type: string
    description: A flag to determine whether or not KerberosRc4Encryption is enabled or disabled.
    default: Enabled
  ldapSigning:
    type: string
    description: A flag to determine whether or not LdapSigning is enabled or disabled.
    default: Disabled
  ntlmV1:
    type: string
    description: A flag to determine whether or not NtlmV1 is enabled or disabled.
    default: Enabled
  syncKerberosPasswords:
    type: string
    description: A flag to determine whether or not SyncKerberosPasswords is enabled or disabled.
    default: Enabled
  syncNtlmPasswords:
    type: string
    description: A flag to determine whether or not SyncNtlmPasswords is enabled or disabled.
    default: Enabled
  syncOnPremPasswords:
    type: string
    description: A flag to determine whether or not SyncOnPremPasswords is enabled or disabled.
    default: Enabled
  tlsV1:
    type: string
    description: A flag to determine whether or not TlsV1 is enabled or disabled.
    default: Enabled
type: object
