$token: azure-native:alertsmanagement/v20230301:PrometheusRuleResolveConfigurationResponse
description: Specifies the Prometheus alert rule configuration.
properties:
  autoResolved:
    type: boolean
    description: Enable alert auto-resolution.
  timeToResolve:
    type: string
    description: Alert auto-resolution timeout.
type: object
