$token: azure-native:hybridcompute/v20221227:OSProfileWindowsConfiguration
description: Specifies the windows configuration for update management.
properties:
  assessmentMode:
    oneOf:
      - type: string
      - $ref: "#/types/azure-native:hybridcompute/v20221227:AssessmentModeTypes"
    description: Specifies the assessment mode.
  patchMode:
    oneOf:
      - type: string
      - $ref: "#/types/azure-native:hybridcompute/v20221227:PatchModeTypes"
    description: Specifies the patch mode.
type: object
