$token: azure-native:appplatform/v20230101preview:ApplicationInsightsAgentVersionsResponse
description: Application Insights agent versions properties payload
properties:
  java:
    type: string
    description: Indicates the version of application insight java agent
type: object
required:
  - java
