$token: azure-native:appplatform/v20230101preview:ApplicationAcceleratorResourceRequestsResponse
properties:
  cpu:
    type: string
    description: Cpu allocated to each application accelerator component. 1 core can be represented by 1 or 1000m
  instanceCount:
    type: integer
    description: Instance count of the application accelerator component.
  memory:
    type: string
    description: Memory allocated to each application accelerator component. 1 GB can be represented by 1Gi or 1024Mi.
type: object
required:
  - cpu
  - instanceCount
  - memory
