$token: azure-native:appplatform/v20230101preview:GatewayPropertiesResponseEnvironmentVariables
description: Environment variables of Spring Cloud Gateway
properties:
  properties:
    type: object
    additionalProperties:
      type: string
    description: Non-sensitive properties
  secrets:
    type: object
    additionalProperties:
      type: string
    description: Sensitive properties
type: object
