$token: azure-native:security/v20230301preview:DefenderForServersGcpOfferingConfigurationConfiguration
description: configuration for Vulnerability Assessment autoprovisioning
properties:
  type:
    oneOf:
      - type: string
      - $ref: "#/types/azure-native:security/v20230301preview:Type"
    description: The Vulnerability Assessment solution to be provisioned. Can be either 'TVM' or 'Qualys'
type: object
