$token: azure-native:signalrservice:ServerlessSettingsResponse
description: Serverless settings.
properties:
  connectionTimeoutInSeconds:
    type: integer
    description: "Gets or sets Client Connection Timeout. Optional to be set.\r

      Value in seconds.\r

      Default value is 30 seconds.\r

      Customer should set the timeout to a shorter period if messages are expected to be sent in shorter intervals,\r

      and want the client to disconnect more quickly after the last message is sent.\r

      You can set the timeout to a longer period if messages are expected to be sent in longer intervals,\r

      and they want to keep the same client connection alive during this session.\r

      The service considers the client disconnected if it hasn't received a message (including keep-alive) in this interval."
    default: 30
type: object
