$token: azure-native:network/v20220901:DdosSettingsResponse
description: Contains the DDoS protection settings of the public IP.
properties:
  ddosProtectionPlan:
    type: object
    $ref: "#/types/azure-native:network/v20220901:SubResourceResponse"
    description: The DDoS protection plan associated with the public IP. Can only be set if ProtectionMode is Enabled
  protectionMode:
    type: string
    description: The DDoS protection mode of the public IP
type: object
