$token: azure-native:network/v20220901:SecurityConfigurationRuleProtocol
description: Network protocol this rule applies to.
type: string
enum:
  - value: Tcp
  - value: Udp
  - value: Icmp
  - value: Esp
  - value: Any
  - value: Ah
