$token: azure-native:machinelearningservices/v20221201preview:MLAssistConfigurationDisabledResponse
description: Labeling MLAssist configuration definition when MLAssist is disabled
properties:
  mlAssist:
    type: string
    description: |-
      
      Expected value is 'Disabled'.
    const: Disabled
type: object
required:
  - mlAssist
