$token: azure-native:workloads:PrometheusHaClusterProviderInstancePropertiesResponse
description: Gets or sets the PrometheusHaCluster provider properties.
properties:
  clusterName:
    type: string
    description: Gets or sets the clusterName.
  hostname:
    type: string
    description: Gets or sets the target machine name.
  prometheusUrl:
    type: string
    description: URL of the Node Exporter endpoint.
  providerType:
    type: string
    description: |-
      The provider type. For example, the value can be SapHana.
      Expected value is 'PrometheusHaCluster'.
    const: PrometheusHaCluster
  sid:
    type: string
    description: Gets or sets the cluster sid.
  sslCertificateUri:
    type: string
    description: Gets or sets the blob URI to SSL certificate for the HA cluster exporter.
  sslPreference:
    type: string
    description: Gets or sets certificate preference if secure communication is enabled.
type: object
required:
  - providerType
