$token: azure-native:securityinsights/v20230401preview:EventGroupingSettings
description: Event grouping settings property bag.
properties:
  aggregationKind:
    oneOf:
      - type: string
      - $ref: "#/types/azure-native:securityinsights/v20230401preview:EventGroupingAggregationKind"
    description: The event grouping aggregation kinds
type: object
