$token: azure-native:hybridcompute:ConfigurationExtensionResponse
description: Describes properties that can identify extensions.
properties:
  publisher:
    type: string
    description: Publisher of the extension.
  type:
    type: string
    description: Type of the extension.
type: object
required:
  - publisher
  - type
