$token: azure-native:securityinsights/v20221001preview:SettingsStatus
description: The anomaly SecurityMLAnalyticsSettings status
type: string
enum:
  - description: Anomaly settings status in Production mode
    value: Production
  - description: Anomaly settings status in Flighting mode
    value: Flighting
