$token: azure-native:machinelearningservices/v20230201preview:EnvironmentVariableType
description: "Type of the Environment Variable. Possible values are: local - For local variable"
type: string
enum:
  - value: local
