$token: azure-native:machinelearningservices/v20230201preview:LabelingDataConfigurationResponse
description: Labeling data configuration definition
properties:
  dataId:
    type: string
    description: Resource Id of the data asset to perform labeling.
  incrementalDataRefresh:
    type: string
    description: Indicates whether to enable incremental data refresh.
    default: Disabled
type: object
