$token: azure-native:machinelearningservices/v20230201preview:MLAssistConfigurationEnabled
description: Labeling MLAssist configuration definition when MLAssist is enabled
properties:
  inferencingComputeBinding:
    type: string
    description: "[Required] AML compute binding used in inferencing."
  mlAssist:
    type: string
    description: |-
      
      Expected value is 'Enabled'.
    const: Enabled
  trainingComputeBinding:
    type: string
    description: "[Required] AML compute binding used in training."
type: object
required:
  - inferencingComputeBinding
  - mlAssist
  - trainingComputeBinding
