$token: azure-native:devcenter/v20221111preview:ProjectEnvironmentTypeUpdatePropertiesCreatorRoleAssignment
description: The role definition assigned to the environment creator on backing resources.
properties:
  roles:
    type: array
    items:
      type: string
    description: A map of roles to assign to the environment creator.
type: object
