$token: azure-native:workloads/v20230401:ExternalInstallationSoftwareConfiguration
description: The SAP Software configuration Input when the software is installed externally outside the service.
properties:
  centralServerVmId:
    type: string
    description: The resource ID of the virtual machine containing the central server instance.
  softwareInstallationType:
    type: string
    description: |-
      The SAP software installation Type.
      Expected value is 'External'.
    const: External
type: object
required:
  - softwareInstallationType
