$token: azure-native:automanage:ConfigurationProfileProperties
description: Automanage configuration profile properties.
properties:
  configuration:
    $ref: pulumi.json#/Any
    description: configuration dictionary of the configuration profile.
type: object
