$token: azure-native:managednetworkfabric:L3IsolationDomainPatchPropertiesIpv6Routes
description: aggregateIpv6Route model.
properties:
  prefix:
    type: string
    description: IPv6 Prefix of the aggregate IPv6 Route.
type: object
