$token: azure-native:appplatform:GatewayRouteConfigOpenApiPropertiesResponse
description: OpenAPI properties of Spring Cloud Gateway route config.
properties:
  uri:
    type: string
    description: The URI of OpenAPI specification.
type: object
