$token: azure-native:machinelearningservices/v20230401preview:ComputeInstanceEnvironmentInfoResponse
description: Environment information
properties:
  name:
    type: string
    description: name of environment.
  version:
    type: string
    description: version of environment.
type: object
