$token: azure-native:machinelearningservices/v20230401preview:ComputeInstanceAutologgerSettingsResponse
description: Specifies settings for autologger.
properties:
  mlflowAutologger:
    type: string
    description: Indicates whether mlflow autologger is enabled for notebooks.
type: object
