$token: azure-native:machinelearningservices/v20230401preview:EnvironmentVariable
properties:
  type:
    oneOf:
      - type: string
      - $ref: "#/types/azure-native:machinelearningservices/v20230401preview:EnvironmentVariableType"
    description: "Type of the Environment Variable. Possible values are: local - For local variable"
    default: local
  value:
    type: string
    description: Value of the Environment variable
type: object
