$token: azure-native:machinelearningservices/v20230401preview:SecretConfigurationResponse
description: Secret Configuration definition.
properties:
  uri:
    type: string
    description: "Secret Uri.\r

      Sample Uri : https://myvault.vault.azure.net/secrets/mysecretname/secretversion"
  workspaceSecretName:
    type: string
    description: Name of secret in workspace key vault.
type: object
