$token: azure-native:dataprotection/v20230101:MonitoringSettingsResponse
description: Monitoring Settings
properties:
  azureMonitorAlertSettings:
    type: object
    $ref: "#/types/azure-native:dataprotection/v20230101:AzureMonitorAlertSettingsResponse"
    description: Settings for Azure Monitor based alerts
type: object
