$token: azure-native:dataprotection/v20230101:SoftDeleteSettingsResponse
description: Soft delete related settings
properties:
  retentionDurationInDays:
    type: number
    description: Soft delete retention duration
  state:
    type: string
    description: State of soft delete
type: object
