$token: azure-native:app/v20221101preview:IngressClientCertificateMode
description: Client certificate mode for mTLS authentication. Ignore indicates server drops client certificate on forwarding. Accept indicates server forwards client certificate but does not require a client certificate. Require indicates server requires a client certificate.
type: string
enum:
  - value: ignore
  - value: accept
  - value: require
