$token: azure-native:app/v20221101preview:ManagedEnvironmentStorageProperties
description: Storage properties
properties:
  azureFile:
    type: object
    $ref: "#/types/azure-native:app/v20221101preview:AzureFileProperties"
    description: Azure file properties
type: object
