$token: azure-native:compute/v20230301:UefiSettingsResponse
description: "Specifies the security settings like secure boot and vTPM used while creating the virtual machine. Minimum api-version: 2020-12-01."
properties:
  secureBootEnabled:
    type: boolean
    description: "Specifies whether secure boot should be enabled on the virtual machine. Minimum api-version: 2020-12-01."
  vTpmEnabled:
    type: boolean
    description: "Specifies whether vTPM should be enabled on the virtual machine. Minimum api-version: 2020-12-01."
type: object
