$token: azure-native:storagecache/v20230501:CacheEncryptionSettings
description: Cache encryption settings.
properties:
  keyEncryptionKey:
    type: object
    $ref: "#/types/azure-native:storagecache/v20230501:KeyVaultKeyReference"
    description: Specifies the location of the key encryption key in key vault.
  rotationToLatestKeyVersionEnabled:
    type: boolean
    description: Specifies whether the service will automatically rotate to the newest version of the key in the key vault.
type: object
