$token: azure-native:automanage:ConfigurationProfile
properties:
  location:
    type: string
    description: The geo-location where the resource lives
  name:
    type: string
    description: The name of the resource
  properties:
    type: object
    $ref: "#/types/azure-native:automanage:ConfigurationProfilePropertiesResponse"
    description: Properties of the configuration profile.
  systemData:
    type: object
    $ref: "#/types/azure-native:automanage:SystemDataResponse"
    description: Azure Resource Manager metadata containing createdBy and modifiedBy information.
  tags:
    type: object
    additionalProperties:
      type: string
    description: Resource tags.
  type:
    type: string
    description: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
type: object
required:
  - location
  - name
  - properties
  - systemData
  - type
inputProperties:
  configurationProfileName:
    type: string
    description: Name of the configuration profile.
    willReplaceOnChanges: true
  location:
    type: string
    description: The geo-location where the resource lives
    willReplaceOnChanges: true
  properties:
    type: object
    $ref: "#/types/azure-native:automanage:ConfigurationProfileProperties"
    description: Properties of the configuration profile.
  resourceGroupName:
    type: string
    description: The name of the resource group. The name is case insensitive.
    willReplaceOnChanges: true
  tags:
    type: object
    additionalProperties:
      type: string
    description: Resource tags.
requiredInputs:
  - resourceGroupName
aliases:
  - type: azure-native:automanage/v20210430preview:ConfigurationProfile
  - type: azure-native:automanage/v20220504:ConfigurationProfile
