$token: azure-native:webpubsub/v20230301preview:WebPubSubTlsSettings
description: TLS settings for the resource
properties:
  clientCertEnabled:
    type: boolean
    description: Request client certificate during TLS handshake if enabled. Not supported for free tier. Any input will be ignored for free tier.
    default: false
type: object
