$token: azure-native:containerservice/v20230302preview:IstioIngressGatewayMode
description: Mode of an ingress gateway.
type: string
enum:
  - description: The ingress gateway is assigned a public IP address and is publicly accessible.
    value: External
  - description: The ingress gateway is assigned an internal IP address and cannot is accessed publicly.
    value: Internal
