$token: azure-native:machinelearningservices/v20230401:CosmosDbSettingsResponse
properties:
  collectionsThroughput:
    type: integer
    description: The throughput of the collections in cosmosdb database
type: object
