$token: azure-native:machinelearningservices/v20230401:IdentityConfigurationType
description: "[Required] Specifies the type of identity framework."
type: string
enum:
  - value: Managed
  - value: AMLToken
  - value: UserIdentity
