$token: azure-native:network/v20220501:StaticRoutesConfigResponse
description: Configuration for static routes on this HubVnetConnectionConfiguration for static routes on this HubVnetConnection.
properties:
  propagateStaticRoutes:
    type: boolean
    description: Boolean indicating whether static routes on this connection are automatically propagate to route tables which this connection propagates to.
  vnetLocalRouteOverrideCriteria:
    type: string
    description: Parameter determining whether NVA in spoke vnet is bypassed for traffic with destination in spoke.
type: object
required:
  - propagateStaticRoutes
