$token: azure-native:containerservice/v20230202preview:ControlledValues
description: Controls which resource value autoscaler will change. Default value is RequestsAndLimits.
type: string
enum:
  - description: Autoscaler will control resource requests and limits.
    value: RequestsAndLimits
  - description: Autoscaler will control resource requests only.
    value: RequestsOnly
