$token: azure-native:connectedvmwarevsphere:OsProfileLinuxConfiguration
description: Specifies the linux configuration for update management.
properties:
  assessmentMode:
    type: string
    description: Specifies the assessment mode.
  patchMode:
    type: string
    description: Specifies the patch mode.
type: object
